### ISSUE TITLE
Hovering bottom pixel of cards triggers infinite loop of pick up/release action

### ISSUE THREAD

**Issue by aclist** [Flippworks/3AO_Defects_Enhancements#1]
Hovering the cursor over the bottom pixel of a card in the top toolbar triggers both the "pickup card" and "release card" action, causing the card itself and the tooltip text at the bottom to flicker infinitely.

It seems as if the pickup action lifts the card, causing the cursor to no longer be within the card's bounding box, which in turn triggers the release card action, which puts the card back under the cursor, and so on.

(Naive speculation about the current implementation follows)

Rather than (or in conjunction with) polling if a card object is under the cursor, it seems like it'd be good to allocate an invisible hitbox to the card slot area, so that even if the card pops up out of its container, the cursor would still be considered inside the card's frame, ensuring the release card action is not triggered while this area is occluded.

**Comment by Flippworks** [comment]
Thanks for the feedback.  This is definitely a "I'll get around to fixing that at some point" thing that never happened for some reason.  I will try to fix this in the next update.

**Comment by aclist** [comment]
The game seems interesting so far. I came across this while inspecting the UI and trying to learn its intricacies. It happened several times unintentionally, so I'd venture to guess it's a common occurrence.

**Comment by Flippworks** [comment]
Fixed in version 1.0.0.39
